import path from 'node:path';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { fileURLToPath, pathToFileURL } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const projects=JSON.parse(fs.readFileSync(path.join(root,'data/projects.json'),'utf8'));
const premiumProjects=projects.filter(p=>p.collection==='moscow-premium');
const filters=[...['studio','one-bedroom','family'].map(type=>[type,projects.filter(p=>p.type===type).length]),['moscow-premium',premiumProjects.length],['all',projects.length]];
const output=path.join(root,'output/qa');fs.mkdirSync(output,{recursive:true});
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright') : 'playwright');
const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.PORTFOLIO_CHROMIUM_EXECUTABLE?{executablePath:process.env.PORTFOLIO_CHROMIUM_EXECUTABLE}:{})});
const page=await browser.newPage({viewport:{width:390,height:960}});
const errors=[];const network=[];
page.on('pageerror',error=>errors.push(error.message));
page.on('request',request=>{if(/^https?:/.test(request.url()))network.push(request.url());});
const frame=page.frameLocator('#portfolio');
try{
 await page.goto(pathToFileURL(path.join(root,'output/Safonov_Interiors_Portfolio.html')).href);
 await frame.locator('h1').waitFor();
 assert.equal(await frame.locator('.project-card:visible').count(),projects.length);
 const initialIDs=await frame.locator('.project-card:visible').evaluateAll(cards=>cards.map(c=>c.id.replace(/^project-/,'')));
 assert.deepEqual(initialIDs.slice(0,premiumProjects.length).toSorted(),premiumProjects.map(p=>p.id).toSorted(),'Premium concepts must lead the embedded collection.');
 for(const [filter,count] of filters) {
  await frame.locator(`[data-filter="${filter}"]`).click();
  assert.equal(await frame.locator('.project-card:visible').count(),count);
  assert.equal(await frame.locator('#shown-count').textContent(),String(count));
  assert.equal(await frame.locator(`[data-filter="${filter}"]`).getAttribute('aria-pressed'),'true');
  const visibleIDs=await frame.locator('.project-card:visible').evaluateAll(cards=>cards.map(c=>c.id.replace(/^project-/,'')));
  const expected=projects.filter(p=>filter==='all'||(filter==='moscow-premium'?p.collection==='moscow-premium':p.type===filter)).map(p=>p.id);
  assert.deepEqual(visibleIDs.toSorted(),expected.toSorted(),`Embedded filter ${filter}: incorrect projects.`);
 }
 await frame.locator('[data-set-lang="en"]').click();
 assert((await frame.locator('h1').innerText()).includes('Thoughtful space.'));
 const firstCaseHref=await frame.locator('.project-title').first().getAttribute('href');
 const firstCaseID=firstCaseHref.match(/cases\/([^/]+)\.html$/)?.[1];
 const firstCase=projects.find(p=>p.id===firstCaseID);
 assert(firstCase,'Embedded first project must reference a known concept.');
 assert.equal(firstCase.collection,'moscow-premium');
 await frame.locator('.project-title').first().click();
 await frame.locator('.case-intro').waitFor();
 assert((await frame.locator('h1').innerText()).includes(firstCase.name.en));
 assert.equal(await frame.locator('html').getAttribute('lang'),'en');
 assert((await frame.locator('.source-plan image').getAttribute('href')).startsWith('blob:'));
 await frame.locator('.source-plan image').evaluate(async image=>{const original=new Image();original.src=image.href.baseVal;await original.decode();});
 await frame.locator('[data-lightbox]').click();
 assert.equal(await frame.locator('dialog').evaluate(d=>d.open),true);
 await page.keyboard.press('Escape');
 assert.equal(await frame.locator('dialog').evaluate(d=>d.open),false);
 const nextCaseHref=await frame.locator('.next-title').getAttribute('href');
 const nextCaseID=nextCaseHref.match(/(?:^|\/)([^/]+)\.html$/)?.[1];
 const nextCase=projects.find(p=>p.id===nextCaseID);
 assert(nextCase,'Embedded next project must reference a known concept.');
 await frame.locator('.next-title').click();
 await frame.locator('h1').filter({hasText:nextCase.name.en}).waitFor();
 assert.equal(await frame.locator('html').getAttribute('lang'),'en');
 await frame.locator('.back-link').click();
 await frame.locator('.project-grid').waitFor();
 assert.equal(await frame.locator('.project-card:visible').count(),projects.length);
 assert.equal(await frame.locator('html').getAttribute('lang'),'en');
 await frame.locator('[data-set-lang="ru"]').click();
 await page.screenshot({path:path.join(root,'output/qa/standalone-390.png')});
 assert.deepEqual(errors,[],'Standalone JavaScript errors');
 assert.deepEqual(network,[],'Standalone preview must not depend on network requests');
 const report={status:'PASS',checkedAt:new Date().toISOString(),checks:[`${projects.length} embedded cases; ${premiumProjects.length} Moscow premium concepts`,...filters.map(([filter,count])=>`Filter ${filter}: ${count}`),'RU/EN across routes','Next and back navigation','Original source plan and render Blob assets','Lightbox','No network dependencies'],errors,network};
 fs.writeFileSync(path.join(root,'output/qa/preview-results.json'),JSON.stringify(report,null,2));
 console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
