import path from 'node:path';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { fileURLToPath, pathToFileURL } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright') : 'playwright');
const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.PORTFOLIO_CHROMIUM_EXECUTABLE?{executablePath:process.env.PORTFOLIO_CHROMIUM_EXECUTABLE}:{})});
const page=await browser.newPage({viewport:{width:390,height:960}});
const errors=[];const network=[];
page.on('pageerror',error=>errors.push(error.message));
page.on('request',request=>{if(/^https?:/.test(request.url()))network.push(request.url());});
const frame=page.frameLocator('#portfolio');
try{
 await page.goto(pathToFileURL(path.join(root,'output/Safonov_Interiors_Portfolio.html')).href);
 await frame.locator('h1').waitFor();
 assert.equal(await frame.locator('.project-card:visible').count(),13);
 await frame.locator('[data-filter="studio"]').click();
 assert.equal(await frame.locator('.project-card:visible').count(),3);
 await frame.locator('[data-filter="all"]').click();
 await frame.locator('[data-set-lang="en"]').click();
 assert((await frame.locator('h1').innerText()).includes('Small apartment'));
 await frame.locator('.project-title').first().click();
 await frame.locator('.case-intro').waitFor();
 assert((await frame.locator('h1').innerText()).includes('Quiet light'));
 assert((await frame.locator('.source-plan image').getAttribute('href')).startsWith('blob:'));
 await frame.locator('[data-lightbox]').click();
 assert.equal(await frame.locator('dialog').evaluate(d=>d.open),true);
 await page.keyboard.press('Escape');
 await frame.locator('.next-title').click();
 await frame.locator('h1').filter({hasText:'Terracotta breakfast'}).waitFor();
 await frame.locator('.back-link').click();
 await frame.locator('.project-grid').waitFor();
 assert.equal(await frame.locator('.project-card:visible').count(),13);
 assert.equal(await frame.locator('html').getAttribute('lang'),'en');
 await frame.locator('[data-set-lang="ru"]').click();
 await page.screenshot({path:path.join(root,'output/qa/standalone-390.png')});
 assert.deepEqual(errors,[],'Standalone JavaScript errors');
 assert.deepEqual(network,[],'Standalone preview must not depend on network requests');
 const report={status:'PASS',checkedAt:new Date().toISOString(),checks:['13 embedded cases','Filters','RU/EN across routes','Next and back navigation','Source screenshot and render Blob assets','Lightbox','No network dependencies'],errors,network};
 fs.writeFileSync(path.join(root,'output/qa/preview-results.json'),JSON.stringify(report,null,2));
 console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
